### ISSUE TITLE
Parse the error message when my XML contains Chinese

### ISSUE THREAD

**Issue by xiaoqi7s** [adiralashiva8/robotframework-metrics#49] opened 2018-12-21 03:30 UTC
Parse the error message when my XML contains Chinese，The error message:
------------
Converting .xml to .html file. This may take few minutes...
1 of 6: Capturing dashboard content...
2 of 6: Capturing suite metrics...
3 of 6: Capturing test metrics...
4 of 6: Capturing keyword metrics...Traceback (most recent call last):
  File "robotmetrics.py", line 849, in <module>
    result.visit(KeywordResults())
  File "/Library/Python/2.7/site-packages/robot/result/executionresult.py", line 120, in visit
    visitor.visit_result(self)
  File "/Library/Python/2.7/site-packages/robot/result/visitor.py", line 44, in visit_result
    result.suite.visit(self)
  File "/Library/Python/2.7/site-packages/robot/model/testsuite.py", line 168, in visit
    visitor.visit_suite(self)
  File "/Library/Python/2.7/site-packages/robot/model/visitor.py", line 87, in visit_suite
    suite.tests.visit(self)
  File "/Library/Python/2.7/site-packages/robot/model/itemlist.py", line 72, in visit
    item.visit(visitor)
  File "/Library/Python/2.7/site-packages/robot/model/testcase.py", line 74, in visit
    visitor.visit_test(self)
  File "/Library/Python/2.7/site-packages/robot/model/visitor.py", line 108, in visit_test
    test.keywords.visit(self)
  File "/Library/Python/2.7/site-packages/robot/model/itemlist.py", line 72, in visit
    item.visit(visitor)
  File "/Library/Python/2.7/site-packages/robot/model/keyword.py", line 118, in visit
    visitor.visit_keyword(self)
  File "/Library/Python/2.7/site-packages/robot/model/visitor.py", line 129, in visit_keyword
    if self.start_keyword(kw) is not False:
  File "robotmetrics.py", line 834, in start_keyword
    table_td.string = str(test_name)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
------------

**Comment by adiralashiva8** [comment] 2018-12-21 04:35
Duplicate of https://github.com/adiralashiva8/robotframework-metrics/issues/48

*Use following line after import:*

`reload(sys)`
`sys.setdefaultencoding("utf-8")`

**Closed** 2020-04-09 11:24 UTC
Labels: bug, duplicate
